version: '3.8'

services:
  # O Banco de Dados Central
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres_core
    environment:
      - POSTGRES_USER=kauan_admin
      - POSTGRES_PASSWORD=kauan_ol
      - POSTGRES_DB=architecture_db
    ports:
      - "5432:5432"

  # O Cache de Alta Performance (Elite)
  redis-cache:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  # O Mensageiro para comunicação assíncrona
  rabbitmq-broker:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"   # Protocolo de mensagens
      - "15672:15672" # Painel de controle (Login: guest / guest)
